# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np
arr = np.random.uniform(0, 20, (4, 7))
data_norm = (arr - arr. min ())/ (arr. max () - arr. min ())
data_norm

array([[0.05601009, 0.28605607, 0.05502326, 0.10127701, 0.93350038,
        0.48708999, 0.99931594],
       [0.67987437, 0.82041514, 0.08246763, 1.        , 0.13414817,
        0.        , 0.0332649 ],
       [0.12304791, 0.30001809, 0.59737572, 0.60849982, 0.47612801,
        0.21779315, 0.45452684],
       [0.44021912, 0.40387403, 0.00452733, 0.78624063, 0.25288133,
        0.63529105, 0.74832383]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [2]:
import numpy as np
a = np.random.randint(0, 10, (8, 10))
minn = min(sum(a[i, :]) for i in range(len(a)))
print(minn)

31


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [3]:
import numpy as np
vectors_1 = np.array([1, 2, 3])
vectors_2 = np.array([4, 5, 6])
distance = np.linalg.norm(vectors_1 - vectors_2)
print(distance)

5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [4]:
import numpy as np
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
np.set_printoptions(formatter={'float':'{: 0.3f}'.format})
print(np.linalg.inv(A) @ (C * (-1)) @ np.linalg.inv(B))

[[ 1.000  0.000]
 [-2.000  1.000]
 [ 3.000 -4.000]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [5]:
import numpy as np
a = np.loadtxt('minutes_n_ingredients.csv', dtype = int, delimiter = ',')
a[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [6]:
print('Cреднее значение второго столбца: ', np.mean(a[:, 1]))
print('Mинимум второго столбца: ', min(a[:, 1]))
print('Mаксимум второго столбца: ', max(a[:, 1]))
print('Mедиана второго столбца: ', np.median(a[:, 1]))
print('Cреднее значение третьего столбца: ', np.mean(a[:, 2]))
print('Mинимум третьего столбца: ', min(a[:, 2]))
print('Mаксимум третьего столбца: ', max(a[:, 2]))
print('Mедиана третьего столбца: ', np.median(a[:, 2]))

Cреднее значение второго столбца:  21601.00169
Mинимум второго столбца:  0
Mаксимум второго столбца:  2147483647
Mедиана второго столбца:  40.0
Cреднее значение третьего столбца:  9.05528
Mинимум третьего столбца:  1
Mаксимум третьего столбца:  39
Mедиана третьего столбца:  9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [7]:
np.quantile(a[:, 1], 0.75)

65.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [8]:
zero_count = np.sum(a == 0)
a[a == 0] = 1
print(a)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [9]:
len(np.unique(a))

100544

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [10]:
print(np.unique(a[:, 2]), len(np.unique(a[:, 2])), sep='\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [11]:
a1=[a[i] for i in range(len(a)) if a[i][2]<6]
a1

[array([446597,     15,      5]),
 array([204134,      5,      3]),
 array([25623,     6,     4]),
 array([484223,     18,      4]),
 array([63150,   250,     4]),
 array([70453,    25,     4]),
 array([66842,     2,     4]),
 array([337928,     55,      4]),
 array([140245,      5,      5]),
 array([75313,   603,     5]),
 array([98524,    40,     3]),
 array([377936,     65,      5]),
 array([87295,    20,     3]),
 array([94928,     5,     5]),
 array([210528,     70,      3]),
 array([317583,     65,      4]),
 array([360691,     13,      4]),
 array([229471,     30,      5]),
 array([297759,     65,      5]),
 array([42314,    60,     5]),
 array([341622,     10,      5]),
 array([43341,    40,     5]),
 array([111500,     15,      4]),
 array([271217,     10,      4]),
 array([316184,     15,      5]),
 array([408293,     35,      4]),
 array([56776,    70,     3]),
 array([180800,      5,      3]),
 array([523799,      5,      4]),
 array([145249,     80,      5]),
 array([50737

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [13]:
arr1=[round(arr[i, 2]/arr[i, 1], 3) for i in range(len(arr)) if arr[i, 1]!=0]
np.set_printoptions(formatter={'float':'{: 0.3f}'.format})
print(max(arr1), arr1, sep='\n')

1.927
[0.247, 0.123, 1.927, 0.059]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [14]:
arr[arr[:, 1].argsort()][::-1][:100][:, 2].mean()

3.9515756586327075

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [15]:
from numpy import random as rd
recipes_list = [arr[rd.randint(len(arr))] for i in range(10)]
recipes_list

[array([ 8.860,  8.162,  0.485,  15.512,  5.259,  12.610,  14.783]),
 array([ 8.860,  8.162,  0.485,  15.512,  5.259,  12.610,  14.783]),
 array([ 8.860,  8.162,  0.485,  15.512,  5.259,  12.610,  14.783]),
 array([ 8.860,  8.162,  0.485,  15.512,  5.259,  12.610,  14.783]),
 array([ 2.764,  6.165,  11.881,  12.095,  9.551,  4.585,  9.135]),
 array([ 1.475,  5.897,  1.456,  2.345,  18.343,  9.761,  19.608]),
 array([ 8.860,  8.162,  0.485,  15.512,  5.259,  12.610,  14.783]),
 array([ 2.764,  6.165,  11.881,  12.095,  9.551,  4.585,  9.135]),
 array([ 13.467,  16.169,  1.984,  19.621,  2.977,  0.398,  1.038]),
 array([ 13.467,  16.169,  1.984,  19.621,  2.977,  0.398,  1.038])]

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [16]:
sr_r=np.mean(a[:, 2])
len([a[i] for i in range(len(a)) if a[i, 2]<sr_r])*100/len(a)

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.